### ISSUE TITLE
Reconsider Configuration File functionality

### ISSUE THREAD

**Issue by umadair** [bentley-historical-library/baroque#27]
The current plans for the distribution of BAroQUe are to have it copied from S:\bhl-software to C:\BHL. This happens automatically on login via a RoboCopy command configured by ITS.

RoboCopy uses the /MIR switch, which would cause the local config.ini to be remove or overwritten on each login.

**Comment by eckardm** [comment]
Don't worry about tools, make a .baroque file (or whatever).
