### ISSUE TITLE
Make not finding a destination directory a non-critical error

### ISSUE THREAD

**Issue by eckardm** [bentley-historical-library/baroque#3]
# Describe the bug
Not quite a bug, exactly. And relatively minor. But right now, if the destination directory does not exist, this is treated as a critical error and BAroQUe exits Python. See: [Lines 55-57](https://github.com/bentley-historical-library/baroque/blob/master/baroque/baroque_project.py#L55-L57) in `baroque_project.py`.

# Expected behavior
Other approaches might be to:
- create the destination directory;
- have a destination directory default;
- prompt the user for a destination directory; or
- have some kind of configuration which includes a default destination directory.

There are probably other ways to do it. The basic idea is making it a little less particular. 

# Additional context
See our notes from the Sprint #1 check-in on September 17, 2019.

**Comment by djpillen** [comment]
Addressed in #22
