### ISSUE TITLE
README > Usage section feeback

### ISSUE THREAD

**Issue by MaryseLT** [bentley-historical-library/baroque#41]
Here are my suggestions to simplify the [Usage](https://github.com/bentley-historical-library/baroque#usage) to avoid user confusion based on Tim's and my feedback from the initial user test we participated in:

## Usage
BAroQUe's functionality is implemented in `baroque.py`, which is a command line script that takes a minimum of 3 arguments as its input:

- Required
  - `SOURCE_DIR` > The path to the desired source directory a user wants to validate. Source directories can be either: a shipment, a collection, or an item
  - `EXPORT_DIR` > The path to a corresponding metadata export for the source directory chosen. Contains a previously generated CSV or XLSX file.

- Optional
  - `-d, --destination REPORTS_DIR` > A path to a destination directory where reports and logs will be stored. In the absence of this argument, BAroQUe checks the previously generated configuration file `.baroque` in the current user's home directory for this destination. As a last resort, the optional `REPORTS_DIR` argument defaults to a `reports` directory in the BAroQUe installation's base directory.
  - `-s, -m, -w, or -all` > Validation action(s) to be run against the source directory

| Action | Help |
| --- | --- |
| SOURCE_DIR | Path to a source directory (a shipment, collection, or item) |
| EXPORT_DIR | Path to a metadata export |
| -d / --destination | Denotes optional argument of the path to reports will be set |
| REPORTS_DIR | Optional argument path to a reports directory | 
| -s, --structure | [Validate directory and file structure](https://github.com/bentley-historical-library/baroque#validate-directory-and-file-structure) |
| -m, --mets | [Validate METS XML](https://github.com/bentley-historical-library/baroque#validate-mets-xml)|
| -w, --wav | [Validate WAV BEXT Chunks](https://github.com/bentley-historical-library/baroque#validate-wav-bext-chunks) |
| -all | [Run all validations](https://github.com/bentley-historical-library/baroque#validate-directory-and-file-structure-mets-xml-and-wav-bext-chunks) (-s / --structure, -m / --mets, & -w / --wav) |

**Comment by djpillen** [comment]
The user and technical documentation have been simplified to avoid confusion in #46 and #48
