### ISSUE TITLE
README > Validate All section feedback

### ISSUE THREAD

**Issue by MaryseLT** [bentley-historical-library/baroque#42]
Here are my suggestions to simplify the [Validate directory and file structure, METS XML and WAV BEXT chunks](https://github.com/bentley-historical-library/baroque#validate-directory-and-file-structure-mets-xml-and-wav-bext-chunks) to avoid user confusion based on Tim's and my feedback from the initial user test we participated in. I suggest placing it under the Usage section after removing the command line code example from that section. 

### Validate All
This steps runs all validation checks (Directory and File Structure, METS XML, and WAV BEXT Chunks).

An example of this command to might look like: 

```sh
$ python baroque.py SOURCE_DIR EXPORT_DIR -all
```

_or, with the optional destination argument..._

```sh
$ python baroque.py SOURCE_DIR EXPORT_DIR -d/--destination REPORTS_DIR -all
```

**Comment by djpillen** [comment]
The user and technical documentation have been simplified to avoid confusion in #46 and #48
