### ISSUE TITLE
README > Validate Directory and File Structure section feedback

### ISSUE THREAD

**Issue by MaryseLT** [bentley-historical-library/baroque#43]
Here are my suggestions to simplify the [Validate Directory and File Structure](https://github.com/bentley-historical-library/baroque#validate-directory-and-file-structure) to avoid user confusion based on Tim's and my feedback from the initial user test we participated in:

### Validate Directory and File Structure
This step validates the directory and file structure of the supplied source directory. Content validated to meet the set expectations are:
  - file naming conventions
  - the expected number of different file types exist (e.g., .WAV, .MP3, .XML) 
  - the items found in the SOURCE_DIR match the items supplied in the EXPORT_DIR
  
For more information, see [Structure Validation documentation](docs/Structure_Validation.md).

| Argument | Help |
| --- | --- |
| SOURCE_DIR | Path to a source directory (a shipment, collection, or item) |
| EXPORT_DIR | Path to a metadata export |
| -s, --structure | Validate directory and file structure |

An example of this command might look like:

```sh
$ python baroque.py SOURCE_DIR EXPORT_DIR -s/--structure
```

_or, with the optional destination argument..._

```sh
$ python baroque.py SOURCE_DIR EXPORT_DIR -d/--destination REPORTS_DIR -s/--structure
```

**Comment by djpillen** [comment]
The user and technical documentation have been simplified to avoid confusion in #46 and #48
