### ISSUE TITLE
README > Validate METS XML section feedback

### ISSUE THREAD

**Issue by MaryseLT** [bentley-historical-library/baroque#44]
Here are my suggestions to simplify the [Validate METS XML](hhttps://github.com/bentley-historical-library/baroque#validate-mets-xml) section to avoid user confusion based on Tim's and my feedback from the initial user test we participated in:

### Validate METS XML
This step validates the METS XML for each item supplied in the `SOURCE_DIR`. This includes validating that various sections of the METS XML exist, including `metsHdr`, `amdSec`, `dmdSec`, `fileSec`, `structMap`. 
Other conditions checked are: 
  - confirming the files listed in the file section and the structural map match what was supplied in the `SOURCE_DIR`
  - confirming the descriptive metadata matches what was supplied in the `EXPORT_DIR`

For more information, see [METS Validation documentation](docs/METS_Validation.md).

| Argument | Help |
| --- | --- |
| SOURCE_DIR | Path to a source directory (a shipment, collection, or item) |
| EXPORT_DIR | Path to a metadata export |
| -m, --mets | Validate METS XML |

An example of this command might look like:

```sh
$ python baroque.py SOURCE_DIR EXPORT_DIR -m/--mets 
```

_or, with the optional destination argument..._

```sh
$ python baroque.py SOURCE_DIR EXPORT_DIR -d/--destination REPORTS_DIR -m/--mets
```

**Comment by djpillen** [comment]
The user and technical documentation have been simplified to avoid confusion in #46 and #48
