### ISSUE TITLE
README > Validate WAV BEXT Chunks section feedback

### ISSUE THREAD

**Issue by MaryseLT** [bentley-historical-library/baroque#45]
Here are my suggestions to simplify the [Validate WAV BEXT Chunks](https://github.com/bentley-historical-library/baroque#validate-wav-bext-chunks) section to avoid user confusion based on Tim's and my feedback from the initial user test we participated in:

### Validate WAV BEXT Chunks
This step validates each WAV file in an item's embedded BEXT chunk. 
This validation checks for:
  - confirming that various bits of metadata exist 
    - e.g., `TimeReference` and `CodingHistory` 
  - the value of various bits of metadata match what's expected, for example:
    - `Description` matches the `ItemTitle` field in the metadata export
    - `OriginatorReference` follows the appropriate convention
  - that various bits of metadata can be recognized as times or dates 
    - e.g., `OriginationTime` and `OriginationDate`

For more information, see [BEXT Validation documentation](docs/BEXT_Validation.md).

| Argument | Help |
| --- | --- |
| SOURCE_DIR | Path to a source directory (a shipment, collection, or item) |
| EXPORT_DIR | Path to a metadata export |
| -w, --wav | Validate WAV BEXT chunk |

An example of this command might look like:

```sh
$ python baroque.py SOURCE_DIR EXPORT_DIR -w/--wav
```

_or, with the optional destination argument..._

```sh
$ python baroque.py SOURCE_DIR EXPORT_DIR -d/--destination REPORTS_DIR -w/--wav
```

**Comment by djpillen** [comment]
The user and technical documentation have been simplified to avoid confusion in #46 and #48
